<a href="https://colab.research.google.com/github/taufique97alam-arch/python_codes/blob/main/Copy_of_taufique.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([(3,-3,4),(1,0,6),(-7,2,-5)])
b=np.array([(6,0,0),(-4,-1,8),(5,-1,8)])
#matrix
print("A=",a)
print("B=",b)
#addition
print("addition of A and B:-",a+b)
#multiplication
print("multiplication of A and B:-",np.dot(a,b))
#diagonal
print("diagonal of matrix A :-",np.diagonal(a))
print("diagonal of matrix b :-",np.diagonal(b))
#transpose
print("trandpose of matrix A :-",np.transpose(a))
print("transpose of matrix b :-",np.transpose(b))
#inverse
try:
  print("inverse of matrix A :-",np.linalg.inv(a))
except:
  print("matrix A is singular")
try:
  print("inverse of matrix b :-",np.linalg.inv(b))
except:
  print("matrix b is singular")
#rank
print("rank of matrix A :-",np.linalg.matrix_rank(a))
print("rank of matrix b :-",np.linalg.matrix_rank(b))
#determinant
print("determinant of matrix A :-",np.linalg.det(a))
print("determinant of matrix b :-",np.linalg.det(b))

A= [[ 3 -3  4]
 [ 1  0  6]
 [-7  2 -5]]
B= [[ 6  0  0]
 [-4 -1  8]
 [ 5 -1  8]]
addition of A and B:- [[ 9 -3  4]
 [-3 -1 14]
 [-2  1  3]]
multiplication of A and B:- [[ 50  -1   8]
 [ 36  -6  48]
 [-75   3 -24]]
diagonal of matrix A :- [ 3  0 -5]
diagonal of matrix b :- [ 6 -1  8]
trandpose of matrix A :- [[ 3  1 -7]
 [-3  0  2]
 [ 4  6 -5]]
transpose of matrix b :- [[ 6 -4  5]
 [ 0 -1 -1]
 [ 0  8  8]]
inverse of matrix A :- [[-0.14457831 -0.08433735 -0.21686747]
 [-0.44578313  0.15662651 -0.1686747 ]
 [ 0.02409639  0.18072289  0.03614458]]
matrix b is singular
rank of matrix A :- 3
rank of matrix b :- 2
determinant of matrix A :- 83.00000000000003
determinant of matrix b :- 0.0
