<a href="https://colab.research.google.com/github/taufique97alam-arch/python_codes/blob/main/matrix_functions_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NAME:TAUFIQUE ALAM
#SYSTEM ID:2025313333
import numpy as np
a=np.array([(3,-3,4),(1,0,6),(-7,2,-5)])
b=np.array([(6,0,0),(-4,-1,8),(5,-1,8)])
#matrix
print("A=",a)
print("B=",b)
#addition
print("addition of A and B:-",(a+b))
#multiplication
print("multiplication of A and B:-",np.dot(a,b))
#diagonal
print("diagonal of matrix A :-",np.diagonal(a))
print("diagonal of matrix b :-",np.diagonal(b))
#transpose
print("trandpose of matrix A :-",np.transpose(a))
print("transpose of matrix b :-",np.transpose(b))
#inverse
try:
  print("inverse of matrix A :-",np.linalg.inv(a))
except:
  print("matrix A is singular")
try:
  print("inverse of matrix b :-",np.linalg.inv(b))
except:
  print("matrix b is singular")
#rank
print("rank of matrix A :-",np.linalg.matrix_rank(a))
print("rank of matrix b :-",np.linalg.matrix_rank(b))
#determinant
print("determinant of matrix A :-",np.linalg.det(a))
print("determinant of matrix b :-",np.linalg.det(b))

A= [[ 3 -3  4]
 [ 1  0  6]
 [-7  2 -5]]
B= [[ 6  0  0]
 [-4 -1  8]
 [ 5 -1  8]]
addition of A and B:- [[ 9 -3  4]
 [-3 -1 14]
 [-2  1  3]]
multiplication of A and B:- [[ 50  -1   8]
 [ 36  -6  48]
 [-75   3 -24]]
diagonal of matrix A :- [ 3  0 -5]
diagonal of matrix b :- [ 6 -1  8]
trandpose of matrix A :- [[ 3  1 -7]
 [-3  0  2]
 [ 4  6 -5]]
transpose of matrix b :- [[ 6 -4  5]
 [ 0 -1 -1]
 [ 0  8  8]]
inverse of matrix A :- [[-0.14457831 -0.08433735 -0.21686747]
 [-0.44578313  0.15662651 -0.1686747 ]
 [ 0.02409639  0.18072289  0.03614458]]
matrix b is singular
rank of matrix A :- 3
rank of matrix b :- 2
determinant of matrix A :- 83.00000000000003
determinant of matrix b :- 0.0


In [ ]:
#NAME:TAUFIQUE ALAM
#SYSTEM ID:2025313333
#To solve a system of linear equation
import numpy as np
A=np.array([[2,-3,4],[0,-4,-8],[4,8,1]])
b=np.array([[4],[7],[-5]])
x=np.linalg.solve(A,b)
print("solution:",x)

solution: [[ 1.01785714]
 [-1.09285714]
 [-0.32857143]]


In [ ]:
#NAME:TAUFIQUE ALAM
#SYSTEM ID:2025313333
#vector operation and similarity
import numpy as np
#define vector
v1=np.array([2,4,6])
v2=np.array([1,3,5])
#1. dot product
dot_product=np.dot(v1,v2)
print("dot product=",dot_product)
#2. scalar multiplication
scalar_mul=2*v1
print("scalar multiplicatio=",scalar_mul)
#3. cosine similarity (using numPy)
cos_sim_numpy=np.dot(v1,v2)/ (np.linalg.norm(v1)*np.linalg.norm(v2))
print("cosine similarity (using numPy)=",cos_sim_numpy)
#cosine similarity (manual formula)
dot_manual=sum(v1[i]*v2[i]for i in range(len(v1)))
norm_v1=(sum(v1[i]**2 for i in range(len(v1))))**0.5
norm_v2=(sum(v2[i]**2 for i in range(len(v2))))**0.5
cos_sim_manual=dot_manual/(norm_v1 * norm_v2)
print("cosine similarity (manual formula)=",cos_sim_manual)

dot product= 44
scalar multiplicatio= [ 4  8 12]
cosine similarity (using numPy)= 0.9938586931957764
cosine similarity (manual formula)= 0.9938586931957764
